PingPong: 
	gcc -Wall -o PingPong ppos_core.c queue.c pingpong-semaphore.c

PingPong_Race: 
	gcc -Wall -o PingPong_Race ppos_core.c queue.c pingpong-racecond.c

DEBUGPingPong: 
	gcc -Wall -o DEBUGPingPong -DDEBUG ppos_core.c queue.c pingpong-semaphore.c

DEBUGPingPong_Race: 
	gcc -Wall -o DEBUGPingPong_Race -DDEBUG ppos_core.c queue.c pingpong-racecond.c 


