teste1: 
	gcc -Wall -o PingPong ppos_core.c queue.c pingpong-contab-prio.c

teste2: 
	gcc -Wall -o PingPong ppos_core.c queue.c pingpong-contab.c

DEBUGteste1:
	gcc -Wall -o DEBUGPingPong -DDEBUG ppos_core.c queue.c pingpong-contab-prio.c 

DEBUGteste2:
	gcc -Wall -o DEBUGPingPong -DDEBUG ppos_core.c queue.c pingpong-contab.c 


